### ISSUE TITLE
不同跟踪场景的性能评估

### ISSUE THREAD

**Issue by sunqimin** [WenRuiCai/HIPTrack#1]
你好，我想请问论文里的figure 5是怎么做的呢，就是如何评估不同跟踪场景的性能呢？因为我没有找到关于lasot数据集中不同跟踪场景视频的一个分类合辑，所以不太清楚怎么去做

**Comment by WenRuiCai** [comment]
Thank you for your question! You can find the answer to your question in the official [LaSOT evaluation tool](https://github.com/HengLan/LaSOT_Evaluation_Toolkit/tree/master).

In the evaluation tool, each video has an attribute annotation file (https://github.com/HengLan/LaSOT_Evaluation_Toolkit/tree/master/annos/att) containing 14 values, each either 1 or 0, representing which type of scene the video belongs to. And you can find the specific category assignments in the evaluation files of the repository.
