### ISSUE TITLE
Something difference between paper and code

### ISSUE THREAD

**Issue by lixueqidaytoy** [WenRuiCai/HIPTrack#3]
Hello, your work is impressive. I have read your paper and the code. I find something different between the paper and code.
1) The conv layer used in FeatureFusionBlock. It uses 3x3 conv layer rather than 1x1 conv as Figure 4.
2) The input of SpatialGate. It uses the output of ChannelGate as input rather than the output of ResBlock1.
```python
def forward(self, x):
   x_out = self.ChannelGate(x)
   if not self.no_spatial:
        x_out = self.SpatialGate(x_out)  
   return x_out
```
3) The method of caculating the similarity score between prompt key and query. It dosen't use L2 distance as paper discribed. Would you please provide more explanation of the method used in code? I'm very interested in it. 
```python
# See supplementary material  
a_sq = mk.pow(2).sum(1).unsqueeze(2)  
ab = mk.transpose(1, 2) @ qk  
affinity = (2*ab-a_sq) / math.sqrt(CK) 
```
 waiting for your reply.

**Comment by WenRuiCai** [comment]
Thank you for your question! Regarding points 1 and 2, we have made minor adjustments to the code, but the impact is minimal. Please refer to the code for the definitive implementation.
Regarding points 3. In the code, it is the expansion and simplified form of the square formula. The specific steps are:
![Uploading 20240813-145201.jpeg…]()

**Comment by WenRuiCai** [comment]
Thank you for your question! Regarding points 1 and 2, we have made minor adjustments to the code, but the impact is minimal. Please refer to the code for the definitive implementation.
Regarding points 3. In the code, it is the expansion and simplified form of the square formula. The specific steps are:
![20240813-145201](https://github.com/user-attachments/assets/1df35a5b-a002-415a-9a2b-58014dd929cf)

**Comment by lixueqidaytoy** [comment]
老哥，靠谱👍👍
非常感谢！！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WenRuiCai/HIPTrack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月13日(星期二) 下午3:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WenRuiCai/HIPTrack] Something difference between paper and code (Issue #3)





 
Thank you for your question! Regarding points 1 and 2, we have made minor adjustments to the code, but the impact is minimal. Please refer to the code for the definitive implementation.
 Regarding points 3. In the code, it is the expansion and simplified form of the square formula. The specific steps are:
 20240813-145201.jpeg (view on web)

**Comment by lixueqidaytoy** [comment]
Sorry, but I still have some questions. The '@' symbol represents matrix multiplication, but 'mk.pow(2)' is an element-wise operation on a matrix. Is there a contradiction between these two types of operations? My understanding is that the L2 distance is an element-wise operation on a matrix, which does not involve matrix multiplication.

**Comment by WenRuiCai** [comment]
There is no conflict between them, because according to the expansion formula, we only need to calculate the squared norm of each vector `mk` and the dot product between `mk` and `qk` vectors. The former is calculated by the sum of element-wise square, and the latter is calculated by matrix multiplication.
At the same time, pytorch supports addition and subtraction of A tensor with shape [B N 1] and B tensor with shape [B N N], which is equivalent to A.repeat(1,1,N) + B
